config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :places
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  root "places#index" # шукає контролер welcome з екшином(методом) index
  get 'about', to: 'welcome#about'
  get 'biking', to: 'places#index'
  get 'climbing', to: 'places#index'
  get 'skiing', to: 'places#index'
  get 'backpacking', to: 'places#index'
  get 'other', to: 'places#index'
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md

    can :read, Place
    cannot :read, Place, published_at: nil

    return unless user.present?

    can :create, Place
    can :read, Place, author_id: user.id 
    can :edit, Place, author_id: user.id
    can :destroy, Place, author_id: user.id
  end
end

    # can :read, Place
    # cannot :read, Place, published_at: nil

    # return unless user.present?

    # can :create, Place
    # can :read, Place, author_id: user.id
    # can :edit, Place, author_id: user.id, published_at: nil
    # can :destroy, Place, author_id: user.id, published_at: nil

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable


  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  
end

app/models/place.rb
class Place < ApplicationRecord

    belongs_to :author, class_name: 'User', foreign_key: :author_id
    has_one_attached :preview_img

    validates :preview_img, presence: true
    validates :description, presence: true

    def self.ransackable_attributes(auth_object = nil)
        ["author_id", "created_at", "description", "id", "id_value", "published_at", "updated_at"]
    end

    def self.ransackable_associations(auth_object = nil)
        ["author", "preview_img_attachment", "preview_img_blob"]
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :places, foreign_key: :author_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: %i[ show edit update destroy ]

  def index
    @places = Place.all
    
  end

  def show
    
  end

  def new
    @place = Place.new
    authorize! :create, @place
  end

  def edit
    authorize! :edit, @place
  end

  def create
    @place = current_user.places.build(place_params)
    authorize! :create, @place

    respond_to do |format|
      if @place.save
        format.html { redirect_to place_url(@place), notice: "Place was successfully created." }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    authorize! :edit, @place

    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to place_url(@place), notice: "Place was successfully updated." }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize! :destroy, @place

    @place.destroy!

    respond_to do |format|
      format.html { redirect_to places_url, notice: "Place was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_place
      @place = Place.find(params[:id])
    end

    def place_params
      params.require(:place).permit(:description, :preview_img)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController # назва контролера 'welcome' має співпадати з назвою каталогу (папки) (views/welcome)
    def index # назва методу (екшину) 'index' має співпадати з назвою файлу, що розташований в каталозі view/welcome (index.html.erb)
        render 'welcome/index'
    end

    def about 
        render 'welcome/about'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/header_helper.rb
module HeaderHelper
    def current_link_class(path)
        current_page?(path) ? 'nav-link px-2 text-secondary' : 'nav-link px-2 text-white'
    end
end




# module ApplicationHelper
#     def current_link_class(action)
#         current_page?(controller: 'places', action: 'biking') ? 'text-secondary' : 'text-white'
#     end
# end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/layouts/_flash_message.html.erb
<p class="notice text-center" style="color: green"><%= notice %></p>
<p class="alert text-center" style="color: red"><%= alert %></p>

app/views/layouts/_footer.html.erb
  <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
  <symbol id="bootstrap" viewBox="0 0 118 94">
    <title>Bootstrap</title>
    <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
  </symbol>
  <symbol id="facebook" viewBox="0 0 16 16">
    <path d="M16 8.049c0-4.446-3.582-8.05-8-8.05C3.58 0-.002 3.603-.002 8.05c0 4.017 2.926 7.347 6.75 7.951v-5.625h-2.03V8.05H6.75V6.275c0-2.017 1.195-3.131 3.022-3.131.876 0 1.791.157 1.791.157v1.98h-1.009c-.993 0-1.303.621-1.303 1.258v1.51h2.218l-.354 2.326H9.25V16c3.824-.604 6.75-3.934 6.75-7.951z"/>
  </symbol>
  <symbol id="instagram" viewBox="0 0 16 16">
      <path d="M8 0C5.829 0 5.556.01 4.703.048 3.85.088 3.269.222 2.76.42a3.917 3.917 0 0 0-1.417.923A3.927 3.927 0 0 0 .42 2.76C.222 3.268.087 3.85.048 4.7.01 5.555 0 5.827 0 8.001c0 2.172.01 2.444.048 3.297.04.852.174 1.433.372 1.942.205.526.478.972.923 1.417.444.445.89.719 1.416.923.51.198 1.09.333 1.942.372C5.555 15.99 5.827 16 8 16s2.444-.01 3.298-.048c.851-.04 1.434-.174 1.943-.372a3.916 3.916 0 0 0 1.416-.923c.445-.445.718-.891.923-1.417.197-.509.332-1.09.372-1.942C15.99 10.445 16 10.173 16 8s-.01-2.445-.048-3.299c-.04-.851-.175-1.433-.372-1.941a3.926 3.926 0 0 0-.923-1.417A3.911 3.911 0 0 0 13.24.42c-.51-.198-1.092-.333-1.943-.372C10.443.01 10.172 0 7.998 0h.003zm-.717 1.442h.718c2.136 0 2.389.007 3.232.046.78.035 1.204.166 1.486.275.373.145.64.319.92.599.28.28.453.546.598.92.11.281.24.705.275 1.485.039.843.047 1.096.047 3.231s-.008 2.389-.047 3.232c-.035.78-.166 1.203-.275 1.485a2.47 2.47 0 0 1-.599.919c-.28.28-.546.453-.92.598-.28.11-.704.24-1.485.276-.843.038-1.096.047-3.232.047s-2.39-.009-3.233-.047c-.78-.036-1.203-.166-1.485-.276a2.478 2.478 0 0 1-.92-.598 2.48 2.48 0 0 1-.6-.92c-.109-.281-.24-.705-.275-1.485-.038-.843-.046-1.096-.046-3.233 0-2.136.008-2.388.046-3.231.036-.78.166-1.204.276-1.486.145-.373.319-.64.599-.92.28-.28.546-.453.92-.598.282-.11.705-.24 1.485-.276.738-.034 1.024-.044 2.515-.045v.002zm4.988 1.328a.96.96 0 1 0 0 1.92.96.96 0 0 0 0-1.92zm-4.27 1.122a4.109 4.109 0 1 0 0 8.217 4.109 4.109 0 0 0 0-8.217zm0 1.441a2.667 2.667 0 1 1 0 5.334 2.667 2.667 0 0 1 0-5.334z"/>
  </symbol>
</svg>



<footer  class="bg-body-tertiary d-flex flex-wrap justify-content-between align-items-center py-3 border-top ">
    <div class="col-md-4 d-flex align-items-center">
      <span class="mb-3 mb-md-0 text-body-secondary offset-3">  <%= Date.today.year %> Outdoor Activities</span>
    </div>

    <ul class=" justify-content-end list-unstyled d-flex offset-3">
      <li class="ms-3"><a class="text-body-secondary" href="https://www.instagram.com/"><svg class="bi" width="24" height="24"><use xlink:href="#instagram"/></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="https://www.facebook.com/"><svg class="bi" width="24" height="24"><use xlink:href="#facebook"/></svg></a></li>
      <li class="ms-3"><a class="text-body-secondary" href="https://www.facebook.com/"><svg class="bi" width="24" height="24">< /></svg></a></li>
    </ul>
</footer>

app/views/layouts/application.html.erb
<%# Це головний шаблон наших всіх VIEW %>

<!DOCTYPE html>
<html>
  <head>
    <title>Mountain2024</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body> <%# відображає всі інші сторінки, які ми передаємо через yield %>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash_message' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place) do |form| %>
  <% if place.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
        <% place.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<div class="borderblock container row col-4 offset-4"> 
  <div class="text-center">
    <br>
    <div class="offset-2">
      <%= form.label :preview_image, style: "display: none" %>
      <%= form.file_field :preview_img %>
    </div>
  
    <br> 
   
    <div class="text-center"> 
      <%= form.label :description, style: "display: block"%>
      <%= form.text_field :description %>
    </div>
    <br> 
  


    <div class="form-group text-center">
      <button type="button" ><%= form.submit %></button>
    </div>


    <br> 
  </div>
</div>



<% end %>

app/views/places/_index_place.html .erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Description:</strong>
    <%= place.description %>
  </p>
</div>

app/views/places/_index_place_draft.html .erb
<div id="<%= dom_id place %>">
  <p>
    <strong>Description:</strong>
    <%= place.description %>
  </p>
</div>

app/views/places/_place.html.erb
<div class="col" id="<%= dom_id place %>">

  <div class="card shadow-sm">
    <%- if place.preview_img.present? %>
      <%= image_tag place.preview_img %>
    <% else %> 
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail" preserveAspectRatio="xMidYMid slice" focusable="false"><title>Placeholder</title><rect width="100%" height="100%" fill="#55595c"/><text x="50%" y="50%" fill="#eceeef" dy=".3em">Thumbnail</text></svg>
    <% end %>  
    <div class="card-body">
       <p class="card-text"><%= place.description %>.</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <%= link_to place do%>
            <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <% end %>
          <% if can? :edit, place %>
            <%= link_to edit_place_path(place) do%>
              <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
            <% end %>
          <% end %>
        </div>
        <small class="text-body-secondary"><%= place.created_at.strftime("%Y-%m-%d %H:%M") %></small>
      </div>
    </div>
  </div>
</div>

app/views/places/edit.html.erb
<div class="text-center">
  <h1>Editing place</h1>
</div>

<%= render "form", place: @place %>


<br>

<div class="text-center">
  <%= link_to places_path do %>
    <button type="button" class="btn btn-dark"><%= t('places.buttons.back') %></button>
  <% end %>

  <%= link_to @place do %>
    <button type="button" class="btn btn-dark"><%= t('places.buttons.view') %></button>
  <% end %>

  <%= button_to t('places.buttons.delete'), @place, method: :delete, form_class: 'd-inline', class: 'btn btn-danger' %>

</div>

app/views/places/index.html.erb
<main>
    <div class="container" >
      <div id="photoflexbox">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3" id="places">

          <% @places.each do |place| %>
            <%= render place %>
          <% end %>
        </div>
      </div>
    </div>
</main>

app/views/places/new.html.erb
<div class="text-center" >
  <h1>New place</h1>
</div>


<%= render "form", place: @place %>

<br>

<div class="text-center" >
  <%= link_to places_path do %>
    <button type="button" class="btn btn-dark"><%= t('places.buttons.back') %></button>
  <% end %>
</div>

app/views/places/show.html.erb
<div class="text-center">
  <h1>Viewing place</h1>
</div>

<div id="photo_place" class="text-center" >
  <%= link_to places_path do %>
    <button type="button" class="btn btn-dark"><%= t('places.buttons.back') %></button>
  <% end %>
  <br>
  <br>

  <%= render @place %>
</div> 

app/views/welcome/about.html.erb
<div id="textabout" >

<p class="text-left"> 
    1. In nature, nothing is perfect and everything is perfect. Trees can be contorted, bent in weird ways, and they're still beautiful. –Alice Walker
<br>
<br>
<br>
    2. Forget not that the earth delights to feel your bare feet and the winds long to play with your hair. —Khalil Gibran
<br>
<br>
<br>
    3. Look deep into nature, and then you will understand everything better. —Albert Einstein
<br>
<br>
<br>
    4. Heaven is under our feet as well as over our heads. —Henry David Thoreau
<br>
<br>
<br>
    5. To me a lush carpet of pine needles or spongy grass is more welcome than the most luxurious Persian rug. —Helen Keller
<br>
<br>
<br>
    6. We don’t inherit the earth from our ancestors, we borrow it from our children. —Native American proverb
<br>
<br>
<br>
</p>

</div>

app/views/welcome/index.html.erb
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light"><%= t('welcome.title') %></h1>
          <p class="lead text-body-secondary"><%= t('welcome.description') %></p>      
      </div>
    </div>
  </section>